/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ACE Brand Palette (Navy #002C5F + Amber #FCAC04)
        "primary":                    "#002C5F",
        "primary-dark":               "#001F43",
        "primary-soft":               "#EEF3F9",
        "on-primary":                 "#ffffff",
        "primary-container":          "#081F3E",
        "on-primary-container":       "#A4BFDD",
        "primary-fixed":              "#D6E4F4",
        "primary-fixed-dim":          "#AEC8E7",
        "on-primary-fixed":           "#001F43",
        "on-primary-fixed-variant":   "#204570",
        "inverse-primary":            "#AEC8E7",

        // Signature Amber Accent
        "accent":                     "#FCAC04",
        "accent-hover":               "#E59B00",
        "accent-container":           "#FFF5E0",
        "on-accent":                  "#1A1202",

        "secondary":                  "#4A5568",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#E2E8F0",
        "on-secondary-container":     "#2D3748",
        "secondary-fixed":            "#E2E8F0",
        "secondary-fixed-dim":        "#CBD5E1",
        "on-secondary-fixed":         "#1E293B",
        "on-secondary-fixed-variant": "#475569",

        "tertiary":                   "#002C5F",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#081F3E",
        "on-tertiary-container":      "#A4BFDD",
        "tertiary-fixed":             "#D6E4F4",
        "tertiary-fixed-dim":         "#AEC8E7",
        "on-tertiary-fixed":          "#001F43",
        "on-tertiary-fixed-variant":  "#204570",

        "surface":                    "#f9f9fb",
        "surface-dim":                "#d8dce6",
        "surface-bright":             "#f9f9fb",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f8",
        "surface-container":          "#eaedf4",
        "surface-container-high":     "#e2e6ef",
        "surface-container-highest":  "#d9dfeb",
        "surface-tint":               "#002C5F",
        "surface-variant":            "#d9dfeb",
        "on-surface":                 "#0b1320",
        "on-surface-variant":         "#475266",
        "inverse-surface":            "#1a2230",
        "inverse-on-surface":         "#f0f3f8",

        "background":                 "#f9f9fb",
        "on-background":              "#0b1320",

        "outline":                    "#64748B",
        "outline-variant":            "#D4D8E2",

        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "full":    "0.75rem",
      },
      spacing: {
        "container-max":   "1280px",
        "unit":            "4px",
        "margin-mobile":   "16px",
        "margin-desktop":  "48px",
        "section-gap":     "96px",
        "gutter":          "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg":         ['"Playfair Display"', "Georgia", "serif"],
        "headline-lg":        ['"Playfair Display"', "Georgia", "serif"],
        "headline-lg-mobile": ['"Playfair Display"', "Georgia", "serif"],
        "headline-md":        ['"Playfair Display"', "Georgia", "serif"],
        "body-lg":            ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-md":            ["Geist", "Inter", "system-ui", "sans-serif"],
        "label-sm":           ["Geist", "Inter", "system-ui", "sans-serif"],
        "mono":               ["Geist", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg":         ["64px",  { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":        ["40px",  { lineHeight: "48px",  letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px",  { lineHeight: "40px",  fontWeight: "500" }],
        "headline-md":        ["24px",  { lineHeight: "32px",  fontWeight: "500" }],
        "body-lg":            ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":            ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "label-sm":           ["13px",  { lineHeight: "16px",  letterSpacing: "0.02em", fontWeight: "500" }],
        "mono":               ["14px",  { lineHeight: "20px",  fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
