/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Design System Colors (ACE Community Portal)
        "primary":                    "#000000",
        "on-primary":                 "#ffffff",
        "primary-container":          "#1c1b1d",
        "on-primary-container":       "#858386",
        "primary-fixed":              "#e5e1e4",
        "primary-fixed-dim":          "#c8c6c8",
        "on-primary-fixed":           "#1c1b1d",
        "on-primary-fixed-variant":   "#474649",
        "inverse-primary":            "#c8c6c8",

        "secondary":                  "#5d5e66",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#e3e1ec",
        "on-secondary-container":     "#63646c",
        "secondary-fixed":            "#e3e1ec",
        "secondary-fixed-dim":        "#c6c5cf",
        "on-secondary-fixed":         "#1a1b22",
        "on-secondary-fixed-variant": "#46464e",

        "tertiary":                   "#000000",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#1a1c1e",
        "on-tertiary-container":      "#838487",
        "tertiary-fixed":             "#e2e2e5",
        "tertiary-fixed-dim":         "#c6c6c9",
        "on-tertiary-fixed":          "#1a1c1e",
        "on-tertiary-fixed-variant":  "#454749",

        "surface":                    "#f9f9f9",
        "surface-dim":                "#dadada",
        "surface-bright":             "#f9f9f9",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f3f3",
        "surface-container":          "#eeeeee",
        "surface-container-high":     "#e8e8e8",
        "surface-container-highest":  "#e2e2e2",
        "surface-tint":               "#5f5e60",
        "surface-variant":            "#e2e2e2",
        "on-surface":                 "#1a1c1c",
        "on-surface-variant":         "#47464a",
        "inverse-surface":            "#2f3131",
        "inverse-on-surface":         "#f0f1f1",

        "background":                 "#f9f9f9",
        "on-background":              "#1a1c1c",

        "outline":                    "#78767b",
        "outline-variant":            "#c8c5ca",

        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "full":    "0.75rem",
      },
      spacing: {
        "container-max":   "1280px",
        "unit":            "4px",
        "margin-mobile":   "16px",
        "margin-desktop":  "48px",
        "section-gap":     "96px",
        "gutter":          "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg":         ['"Playfair Display"', "Georgia", "serif"],
        "headline-lg":        ['"Playfair Display"', "Georgia", "serif"],
        "headline-lg-mobile": ['"Playfair Display"', "Georgia", "serif"],
        "headline-md":        ['"Playfair Display"', "Georgia", "serif"],
        "body-lg":            ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-md":            ["Geist", "Inter", "system-ui", "sans-serif"],
        "label-sm":           ["Geist", "Inter", "system-ui", "sans-serif"],
        "mono":               ["Geist", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg":         ["64px",  { lineHeight: "72px",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":        ["40px",  { lineHeight: "48px",  letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px",  { lineHeight: "40px",  fontWeight: "500" }],
        "headline-md":        ["24px",  { lineHeight: "32px",  fontWeight: "500" }],
        "body-lg":            ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":            ["16px",  { lineHeight: "24px",  fontWeight: "400" }],
        "label-sm":           ["13px",  { lineHeight: "16px",  letterSpacing: "0.02em", fontWeight: "500" }],
        "mono":               ["14px",  { lineHeight: "20px",  fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
