import faheem from '../../assets/alumnis/faheem.jpeg';
import faizalR from '../../assets/candidates/faizalR.jpeg';

export const ALUMNI_MEMBERS = [
  // September 2026
  {
    id: 1,
    name: 'Faizal Raheem',
    role: 'Software Engineer',
    domain: 'MERN',
    company: 'Non-Disclosable',
    placedOn: 'September 2026',
    pkg: '30+ LPA',
    spotlight: true,
    quote: 'Secured a premier 30+ LPA role by mastering full-stack MERN architecture and building resilient high-throughput systems.',
    img: faizalR,
  },
  {
    id: 2,
    name: 'Zameer Ahammed',
    role: 'Software Engineer',
    domain: 'MERN',
    company: 'Non-Disclosable',
    placedOn: 'September 2026',
    pkg: '30+ LPA',
    spotlight: true,
    quote: 'Achieved a landmark 30+ LPA placement through rigorous mastery of scalable web infrastructure and software craft at ACE.',
    img: 'https://media.licdn.com/dms/image/v2/D4D03AQGKZqsGi5MCQQ/profile-displayphoto-scale_400_400/B4DZ3uWzTJKAAg-/0/1777820453298?e=1790208000&v=beta&t=DZKhcLnf2LuPkT0bo62SSXC62lybIF-dpBmEejP7lZ0',
  },
  // August 2026
  {
    id: 3,
    name: 'Abdul Basith',
    role: 'AI Engineer',
    companyRole: 'AI Engineer @ AccuMateAi',
    domain: 'MERN',
    company: 'AccuMateAi',
    placedOn: 'August 2026',
    pkg: 'Non-Disclosable',
    quote: 'The community aspect of ACE was unparalleled. Building complex side projects with peers prepared me perfectly for the fast pace of early-stage startups.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQGmUbk5PjsWsw/profile-displayphoto-shrink_400_400/B56ZboZa9FGgAg-/0/1747655701772?e=1788393600&v=beta&t=fMeiBT5KOpLUVl1NHj2hpLJwWKmJaPKOetI2vxfv5zw',
  },
  // June 2026
  {
    id: 4,
    name: 'Muhammed Shahan P P',
    role: 'Associate Engineer',
    domain: 'Data Science',
    company: 'Non-Disclosable',
    placedOn: 'June 2026',
    pkg: '25+ LPA',
    spotlight: true,
    quote: 'Stepped into an AI Specialist role commanding 25+ LPA, driving machine learning models and intelligent data systems.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQH_RuNd4z8LCA/profile-displayphoto-scale_400_400/B56Zte_R6eHAAk-/0/1766825206303?e=1790208000&v=beta&t=HuHIdmY0letff35VDus54nt9GTnUENZhpEFo_vHpwj4',
  },
  // May 2026
  {
    id: 5,
    name: 'Afzal A',
    role: 'ML Engineer',
    companyRole: 'ML Engineer @ Golgix',
    domain: 'Data Science',
    company: 'Golgix',
    placedOn: 'May 2026',
    pkg: 'Non-Disclosable',
    quote: 'Working with real-world ML datasets and building end-to-end inference pipelines at ACE made the transition to industry seamless.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQEpALUzeH-szA/profile-displayphoto-scale_400_400/B56Z8P7qmxIUAg-/0/1782678728810?e=1790208000&v=beta&t=uo5z3X9CA7U4vbJMkHGwSvAXsokfdMeNVeqdK6DmAX8',
  },
  {
    id: 6,
    name: 'Fizan Muhammed Faisal',
    role: 'Software Engineer',
    companyRole: 'Software Engineer @ Skai Lama',
    domain: 'MERN',
    company: 'Skai Lama',
    placedOn: 'May 2026',
    pkg: 'Non-Disclosable',
    quote: 'Building production architectures with intense peer code reviews helped me step into high-impact engineering from day one.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQHMDBKbaFpFtA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1718249752686?e=1790208000&v=beta&t=3mDzDeVo3YYEJrny8Z5xUAjv1kwp-nf6rbJqddv3cSo',
  },
  {
    id: 7,
    name: 'Faheem Basheer',
    role: 'Software Engineer',
    companyRole: 'Software Engineer @ Skai Lama',
    domain: 'MERN',
    company: 'Skai Lama',
    placedOn: 'May 2026',
    pkg: 'Non-Disclosable',
    quote: 'The peer learning and engineering rigor at ACE set a benchmark that continues to guide my daily work.',
    img: faheem,
  },
  {
    id: 8,
    name: 'Ijas Ahammed',
    role: 'Full-stack Developer',
    companyRole: 'Full-stack Developer @ Kalpas Innovations',
    domain: 'MERN',
    company: 'Kalpas Innovations Pvt Ltd',
    placedOn: 'May 2026',
    pkg: 'Non-Disclosable',
    quote: 'The culture of building scalable web apps from ground up gave me the confidence to deliver production features effortlessly.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQE8aEtjgr_Tgg/profile-displayphoto-scale_400_400/B56ZpKKTMfIcAg-/0/1762180819496?e=1790208000&v=beta&t=EYos3uxI1mB2nmtIKWSw_L_-BF1KCoE9XVxH-N2JTB8',
  },
  {
    id: 9,
    name: 'Anandhu P Raj',
    role: 'ML Engineer',
    domain: 'AI/ML',
    company: 'Non-Disclosable',
    placedOn: 'May 2026',
    pkg: '9 LPA',
    quote: "ACE didn't just teach syntax; it taught us how to think like engineers. The transition to cloud AI environments felt completely natural.",
    img: 'https://media.licdn.com/dms/image/v2/D5603AQHw3q2HIMuprw/profile-displayphoto-shrink_400_400/B56ZRhW5MEHQAg-/0/1736800179613?e=1788393600&v=beta&t=CF2_lvBxOaRf1XofGsbMD9xpkg2O82VjYv5AI37AEqU',
  },
  // April 2026
  {
    id: 10,
    name: 'Amal Deep',
    role: 'DevOps Engineer',
    companyRole: 'DevOps Engineer @ KubeNine',
    domain: 'DevOps',
    company: 'KubeNine',
    placedOn: 'April 2026',
    pkg: 'Non-Disclosable',
    quote: 'The deep focus on cloud systems, containers, and deployment reliability at ACE gave me the exact skillset required in modern DevOps.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQFNrOWdkht72Q/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1727163469555?e=1790208000&v=beta&t=F3-TIGFkwd1q4j4MYy2mWbpldqEH431rvKFj2DP7d60',
  },
  // March 2026
  {
    id: 11,
    name: 'Abhiram S Sajeev',
    role: 'Software Engineer',
    companyRole: 'Software Engineer @ Skai Lama',
    domain: 'MERN',
    company: 'Skai Lama',
    placedOn: 'March 2026',
    pkg: '9 LPA',
    quote: 'The rigorous architectural patterns taught at ACE became my foundation. When scaling distributed systems today, I still fall back on those core principles.',
    img: 'https://media.licdn.com/dms/image/v2/D5603AQGZVqQhBrUFkA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1708889149547?e=1788393600&v=beta&t=-9Poqt6Sd7wzxlWqS_6xBnWp5X2cqKOXg_YMbxwXlag',
  },
];

export const SPOTLIGHT_ALUMNI = ALUMNI_MEMBERS.filter((a) => a.spotlight);

export const ALUMNI_STORIES = ALUMNI_MEMBERS.filter((a) => a.quote && !a.spotlight);

export const ALUMNI_STATS = [
  { value: '11+', label: 'Alumni Placed' },
  { value: '30+ LPA', label: 'Highest Package' },
  { value: '5+', label: 'Partner Companies' },
  { value: '13.45 LPA', label: 'Average Package' },
];
